modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Samarium150/TagHelper/issues"
license="GNU GENERAL PUBLIC LICENSE Version 3"

[[mods]]
    modId="taghelper"
    version="${file.jarVersion}"
    displayName="Tag Helper"
    updateJSONURL="https://raw.githubusercontent.com/Samarium150/TagHelper/main/docs/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/taghelper"
    logoFile="logo.png"
    authors="Samarium"
    description='''
    Mod for editing NBT by commands
    '''
